### ISSUE TITLE
Waiting for ChannelRead callback but channelReadComplete is called

### ISSUE THREAD

**Issue by ranmyfriend** [apple/swift-nio-ssl#104]
**channelReadComplete** is called but still, one event is there to send from the server. How do I debug this? Any idea?

I successfully did handshake to the server and also I will be able to send and receive data from Server. But here, in my case I am sending 4 pin digit to the server and expecting the event in the **channelRead** callback. 2 Events have to get but currently am getting only 1 event. but very very rarely it works. like 1/50 tries I may get 1 time. I don't know how to debug this. Can you please help me to debug this?

Thanks,
Ranjith

**Comment by Lukasa** [comment]
@ranmyfriend the `SSLHandler` will deliver data only when `BoringSSL` claims that the data is entirely available. If a complete TLS record is not available, it will not be delivered.

Are you sure your "one event" does not actually contain both of the events you're expecting?

**Comment by ranmyfriend** [comment]
Yeah, you are correct. Second event data also coming in the first event. Because of very less time delay between these two events. I have handled it. 

Thanks :)
