### ISSUE TITLE
HTTPS Proxy setup issues (OPENSSL_internal:HTTPS_PROXY_REQUEST)

### ISSUE THREAD

**Issue by pseibel** [apple/swift-nio-ssl#106]
I'm trying to setup a swift-nio/swift-nio-ssl based server that is capable of acting as a https proxy server. 
When adding the SSLServerHandler I'm constantly getting 
handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435611 error:1000009b:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST]))
Errors. Any help is highly appreciated :-)

Thanks,
Philipp

**Comment by Lukasa** [comment]
In general when a HTTP proxy is interposed between a client and a server and that client is aware of the proxy, the client will issue a HTTP CONNECT request to establish the connection. This will establish an opaque TCP tunnel through the proxy to the remote peer, at which point TLS will be negotiated over that reverse proxy. This means the proxy itself never terminates the TLS, and so `SSLServerHandler` should not be necessary.

So my question is: when you say "a https proxy server", what specific behaviour do you want to achieve?

**Comment by pseibel** [comment]
Thanks for your quick reply. I'm trying to intercept http/https calls made on a device by setting up a http/https proxy that handles all the requests coming in. I'm not an expert in this area so my terminology might be wrong .... 
My https proxy server should be able pretend to be the receiver of the https request and act as the original target of the request.

**Comment by Lukasa** [comment]
> My https proxy server should be able pretend to be the receiver of the https request and act as the original target of the request.

This is a complex thing to do unless the target turns off its certificate validation.

What you're asking to do is similar to what `mitmproxy` and Charles proxy to do, which is to inject yourself as a man-in-the-middle. If you want to do this in the same way that those two entities do, you need to write code to build an automated certificate authority that can issue new certificates in response to inbound TCP connections. This is quite a lot of code to write, and it's definitely beyond what I can reasonably help you with in a GitHub issue. Suffice to say that this project only provides tools for the TLS: the generation and signing of certificates is outside the scope of this project.

If you're willing to disable certificate validation on the clients, then it gets easier: you can just present a self-signed certificate. What you have to do here is deal with the fact that the client is going to send a CONNECT request to you *before* it attempts to start speaking TLS. In your case this is easy enough to deal with: just respond to the CONNECT request before you add your TLS handler.

Essentially, you want a channel handler that listens for an inbound CONNECT request, adds the SSLHandler behind it, responds with a 200 OK message and then removes itself from the pipeline. Then you should be good to go.

**Comment by Lukasa** [comment]
Of course, if you are interested in just seeing the data more than building the tool, I recommend using mitmproxy or Charles, as they'll work out-of-the-box to achieve what you want to achieve.

**Comment by pseibel** [comment]
I think using self-signed certificate would work for me. Thanks for pointing me in the right direction. Is there any example code that is also dynamically adding and removing handlers that I can take as a starting point?

**Comment by Lukasa** [comment]
There should be plenty, but looking at things like NIO's `HTTPServerUpgradeHandler` shows some example of that code.

**Comment by pseibel** [comment]
Awesome, thanks for your support!
