### ISSUE TITLE
Add support for allowing renegotiation

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-ssl#110]
While TLS renegotiation is basically bad, some users need it for post-handshake auth in HTTPS scenarios (see swift-server/swift-nio-http-client#27). We can allow it with BoringSSL by calling `SSL_set_renegotiate_mode` to `ssl_renegotiate_once`.

We should control this setting via the `TLSConfiguration` struct, and keep the current default behaviour of "forbidden".

**Comment by Lukasa** [comment]
I don't *believe* anything special in the I/O path should be required, but as part of this work we should validate that assumption.

**Comment by weissi** [comment]
CC @markfinlabs
