### ISSUE TITLE
Inconsistency between crashing and throwing error NIOSSLError.unableToAllocateBoringSSLObject

### ISSUE THREAD

**Issue by kevints** [apple/swift-nio-ssl#130]
There are some paths in NIOSSLCertificate that will throw `NIOSSLError.unableToAllocateBoringSSLObject` when BIO APIs return nil and others that will crash the program. We should audit them to ensure that we throw `NIOSSLError.unableToAllocateBoringSSLObject` whenever possible.

**Comment by Lukasa** [comment]
We went the other way, these all crash now.
