### ISSUE TITLE
All versions newer than 2.2.0 fail on Swift 5.0.x

### ISSUE THREAD

**Issue by ktoso** [apple/swift-nio-ssl#146]
When trying to use Swift 5.0.x and swift-nio-ssl in any version higher than `2.2.0` the following error happens (2.2.0 works) on macOS:

```
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      _init_once in urandom.c.o
      _fill_with_entropy in urandom.c.o
ld: symbol(s) not found for architecture x86_64
```

We noticed since we had the dependency as `from:` and when checking things on 5.0 recently we could not compile anymore.

**Comment by Lukasa** [comment]
So this appears to be the result of using a swift.org 5.0 toolchain with an Xcode 11 SDK. That’s really not a supported configuration, and in this case seems to be causing linker issues: the SDK is suggesting a function should exist that is not actually present in the runtime provided by the toolchain and/or operating system.

If you need Swift 5.0 compilation on a newer OS, please use the Swift 5.0 compatibility mode in the Swift 5.1 compiler. Alternatively, if you are using an older OS, Swift 5.0 should work just fine and remains a supported configuration.
