### ISSUE TITLE
[enhancement]Support for PKCS#12 in TLSConfiguration

### ISSUE THREAD

**Issue by pushkarnk** [apple/swift-nio-ssl#17]
Kitura supports certificates in the PKCS#12 format on `macOS`. It'd be great to have that supported by `swift-nio-ssl`.

**Comment by Lukasa** [comment]
Yup, this is a thing we can add. It's a decent chunk of work, but I can add it to my backlog and try to address it soon.

Out of interest, what requirements does Kitura have today regarding PKCS#12 passphrase input? If the user has a PKCS#12-formatted certificate with a passphrase, how does Kitura support the user providing that passphrase?

**Comment by pushkarnk** [comment]
Thanks @Lukasa 

On `macOS` Kitura, while configuring your server to use HTTPS, the user needs to set up their SSL configuration using PKCS#12 certificates (PEM files may be used on Linux). I'm not sure why we mandate PKCS on macOS(may be Secure Transport mandated it?). Though we may want to support PEM files on macOS too, we'd want to continue supporting PKCS.

I can give this a try :)

**Comment by Lukasa** [comment]
I suspect this is a requirement you inherited from Security.framework, yeah. :smile:
