### ISSUE TITLE
deprecate & remove throw NIOSSLError.unableToAllocateBoringSSLObject; replace by crash

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-ssl#173]
instead of `throw NIOSSLError.unableToAllocateBoringSSLObject`, we should (like Swift does for all other failing memory allocations) just crash instead.

**Comment by agnosticdev** [comment]
Thoughts on swapping out `NIOSSLError.unableToAllocateBoringSSLObject` with `fatalError` to force a crash?

**Comment by weissi** [comment]
@agnosticdev yes please :)
