### ISSUE TITLE
Pop unprocessed data on the read path before closing

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-ssl#179]
If the user initiates a close on a NIOSSL handler, it's possible that before the response CLOSE_NOTIFY is received we'll receive some application data (as it was already in flight). When that happens today, we'll be in the `.closing` state which will lead us to call `doShutdownStep`. That is fine, as it goes, but BoringSSL will error if there is unprocessed application data in that stage, which is sad and causes data loss.

A _better_ choice is to follow the same as the normal read path and call `doDecodeData`. That method has a special return value for having received EOF (`zeroReturnError`) and already handles it, correctly issuing a shutdown step. This should therefore totally handle the use-case, with almost no code changes required.

Naturally we'll want a test to be sure of this case, but that's easily done.

**Comment by weissi** [comment]
the error a user would see is

```
NIOSSL.BoringSSLError.sslError([Error: 268435747 error:10000123:SSL routines:OPENSSL_internal:APPLICATION_DATA_ON_SHUTDOWN])
```

**Comment by agnosticdev** [comment]
Is this closed now via https://github.com/apple/swift-nio-ssl/pull/198

**Comment by Lukasa** [comment]
Sure is!
