### ISSUE TITLE
Compile error: Use of unresolved identifier 

### ISSUE THREAD

**Issue by chengenzhao** [apple/swift-nio-ssl#188]
Hi:

We created a new Xcode project and import SwiftyRequest and BlueSocket dependencies, all goes fine until we start compiling the SwiftUI demo project, the Xcode provides compile error: Use of unresolved identifier as you may see the errors below:
<img width="1277" alt="Screen Shot 2020-02-22 at 4 34 00 PM" src="https://user-images.githubusercontent.com/5525436/75089172-27870380-5591-11ea-84ee-e93cac8334d6.png">

Any idea how this happened? 
Is it because we need to "Signing for "Xtrike" requires a development team." ? 

Xcode version: 11.3.1 (11C504)
OS version: 10.15.3 Catalina

Thanks

**Comment by chengenzhao** [comment]
Xcode could find the definition, but it just couldn't recognize it, weird

swift --version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.3.0
 
<img width="1280" alt="Screen Shot 2020-02-22 at 4 44 04 PM" src="https://user-images.githubusercontent.com/5525436/75089329-8e58ec80-5592-11ea-9f37-c2c86312d51f.png">

**Comment by Lukasa** [comment]
This suggests a problem finding the BoringSSL header files. Can you use the build log to show the compiler invocation used to compile that file?

**Comment by chengenzhao** [comment]
This? 
<img width="1279" alt="Screen Shot 2020-02-22 at 5 19 11 PM" src="https://user-images.githubusercontent.com/5525436/75089787-76379c00-5597-11ea-9151-14db42b32be2.png">

**Comment by chengenzhao** [comment]
And I also export the build log here:
[Build Xtrike_2020-02-22T17-14-49.txt](https://github.com/apple/swift-nio-ssl/files/4239050/Build.Xtrike_2020-02-22T17-14-49.txt)

**Comment by chengenzhao** [comment]
I just clean the build folder and rebuild again
this time it works
So it could be the problem of the build cache

Thanks
