### ISSUE TITLE
[Feature request] TLSConfiguration.trustRoots is not flexible enough

### ISSUE THREAD

**Issue by aulanov** [apple/swift-nio-ssl#201]
`TLSConfiguration.trustRoots` is defined as `enum NIOSSLTrustRoots`. That enum can be `.file(String)`, `certificates([NIOSSLCertificate])` or `.default`. Default here means using roots provided by the platform (e.g "/etc/ssl/certs/ca-certificates.crt" on Linux). 

Now the problem is that I cannot use combination of these mechanisms: for example if I want to trust all root certificates provided by the platform, but also some custom ones that I have in my app.

**Comment by Lukasa** [comment]
This seems like a reasonable request!

**Comment by simonjbeaumont** [comment]
I believe this is fixed by #284.

**Comment by Lukasa** [comment]
Agreed.
