### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by Jake-Prickett** [apple/swift-nio-ssl#202]
Hello!

While working to get SwiftGRPC compatible with CocoaPods, it looks like this is the only Pod that hasn't been published that is required. Would it be possible to get a release that includes the updated changes to the imports that allows for Cocoapods to build? 👍 

Thanks!

**Comment by weissi** [comment]
@Jake-Prickett yes, we're working on a release anyway. Basically once #185 is in, we can release

**Comment by weissi** [comment]
I'll work on finishing that today

**Comment by Jake-Prickett** [comment]
@weissi nice, thank you! 👍 No rush!

**Comment by weissi** [comment]
@Jake-Prickett done :)

**Comment by weissi** [comment]
https://github.com/apple/swift-nio-ssl/releases/2.7.0

**Comment by Jake-Prickett** [comment]
Thank you @weissi!
