### ISSUE TITLE
Build failed: 'openssl/conf.h' file not found

### ISSUE THREAD

**Issue by euskadi31** [apple/swift-nio-ssl#203]
macOS: 10.15.3
Swift: 5.1.3
Xcode: 11.3.1
libressl: 3.0.2 (from brew)

**Comment by Lukasa** [comment]
What version of swift-nio-ssl are you using?

**Comment by xianwen** [comment]
I experiencing the same problem:

```
{
        "package": "swift-nio",
        "repositoryURL": "https://github.com/apple/swift-nio.git",
        "state": {
          "branch": null,
          "revision": "8da5c5a4e6c5084c296b9f39dc54f00be146e0fa",
          "version": "1.14.2"
        }
      },
```

**Comment by Lukasa** [comment]
Great, this is a v1 release. You will need either a copy of libressl installed from Homebrew (on a Mac) or to install the `pkgconfig` tool (on Linux).

**Comment by weissi** [comment]
on macOS you might also need to install `pkgconfig` via homebrew and set your `PKG_CONFIG_PATH`:

    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(brew --prefix)/opt/libressl/lib/pkgconfig"

or so. When installing, homebrew outputs the exact command for you.

@xianwen besides that, is there any particular reason you're using SwiftNIO SSL 1.x and not 2.x? In 2.x all this isn't necessary as NIOSSL ships its own TLS implementation (BoringSSL).

**Comment by xianwen** [comment]
Thank you both for the response.

1. `brew install libressl` fixed the problem. Great!
2. It's because I'm not using SwiftNIO directly, it's an indirect dependency of https://github.com/pvzig/SlackKit.git which my project depends on.

**Comment by hdsenevi** [comment]
Hi everyone,

I had the same problem and here are the steps I took to fix it (leaving it here for benefit of others who might face the same issue)

1) `brew install libressl`
   - try building after this, for some it might work. It didn't for me
2) `pkg-config --libs libssl`
   - copy path thats ending with **pkgconfig**
   - lets call this path **LIBRESSL_PATH** just for reference
3) open your **~/.bash_profile** and export **PKG_CONFIG_PATH** with above mentioned **LIBRESSL_PATH**
   - my **~/.bash_profile** looks something along the lines of 
 ```
export PKG_CONFIG_PATH="/PATH_TO_HOME/homebrew/Cellar/libressl/3.1.3/lib/pkgconfig"
```

4) `source ~/.bash_profile`
5) clean xcode derived data folder
6) build the app and voila

**Comment by gangadharbonda** [comment]
The above solution from @hdsenevi  worked for me. Thank you

**Comment by weissi** [comment]
@shreyaspapi you seem to be using a swift-nio-ssl 1.x version which means you're using SwiftNIO 1.x as well which is [end of life](https://github.com/apple/swift-nio#swiftnio-1). You should strongly suggest updating to SwiftNIO 2.x which was released about 3 years ago :).
