### ISSUE TITLE
NIO doesn't match Network.framework's SNI validation

### ISSUE THREAD

**Issue by dimitribouniol** [apple/swift-nio-ssl#219]
Passing an empty string (`""`, not `nil`) as the hostname for SNI validation (for instance, when making a socket connection and using TLS) in `NIOSSLClientHandler` throws an `NIOSSLExtraError.invalidSNIHostname` error, but does not do the same in Network.framework. NIO seems to verify that the SNI is at least one character long.

I'm not sure which framework is correct here, but the behavior I'm seeing can be verified in AsyncHTTPClient by running the `testHTTPSPlusUNIX()` test with the environmental variable `DISABLE_TS_TESTS` unset (Use Network.framework), and set to `true` (Use NIO's TLS handling) from this intermediate commit: https://github.com/swift-server/async-http-client/pull/228/commits/fab2b8c41fde324af75b62290f0681d8baa9bceb

This has since been addressed in AsyncHTTPClient, just referencing it here as a potential area of investigation. cc/ @weissi

Relevant code:
https://github.com/apple/swift-nio-ssl/blob/584c0d06c46233d3e1759695e5eff495b12edcd2/Sources/NIOSSL/NIOSSLClientHandler.swift#L39-L41

**Comment by Lukasa** [comment]
So both implementations agree that the empty string is an invalid choice for SNI value and hostname validation. For example, consider this code:

```
import Foundation
import Dispatch
import Network
import Security

func main() {
    let q = DispatchQueue(label: "networking")
    let tlsOptions = NWProtocolTLS.Options()
    sec_protocol_options_set_tls_server_name(tlsOptions.securityProtocolOptions, "")
    let conn = NWConnection(host: "httpbin.org", port: 443, using: NWParameters(tls: tlsOptions))
    conn.start(queue: q)
    conn.receive(minimumIncompleteLength: 1, maximumLength: 1024) { data, context, isComplete, error in
        ()
    }
}

main()
dispatchMain()
```

This code that sets the server name to the empty string will cause the SNI extension to be set to "httpbin.org". That is, Network.framework will ignore the manual override.

This is a reasonable choice given Network.framework's API limitation: `sec_protocol_options_set_tls_server_name` does not accept a nullable pointer for the server name, so it's not possible to pass `nil` to that method. That means it literally does not have the same API as SwiftNIO SSL. In cases where we'd normally pass `nil` to SwiftNIO SSL we must instead not call `sec_protocol_options_set_tls_server_name`.

I don't think it's reasonable for SwiftNIO SSL to silently fail here: the loud error is appropriate. Network.framework could do that too, if it wanted: please feel free to file a report using Feedback Assistant if you'd like to see that change in behaviour.

**Comment by weissi** [comment]
@Lukasa couldn't we _emit_ an error if we see the empty string in NIOTS?

**Comment by Lukasa** [comment]
We don't have an API for this configuration, we delegate to Security.framework directly.

**Comment by weissi** [comment]
@Lukasa oh right, I forgot we make the user configure the `sec_options` or whatever it is _before_ handing it to us.

**Comment by weissi** [comment]
agree with you then, not much we can do.

**Comment by dimitribouniol** [comment]
@Lukasa Makes sense considering the limitation — thank you for looking further into it. Although I don't personally need Network.framwork to match in this scenario, would you still like a Feedback # for internal tracking?

**Comment by Lukasa** [comment]
If you're not worried about it then it's fine, there are other issues tracking this.
