### ISSUE TITLE
Fail to set custom verification callback on macOS/iOS/...

### ISSUE THREAD

**Issue by schmittner** [apple/swift-nio-ssl#223]
The following MWE fails with an assertion error when trying to use a `customVerificationCallback` in NIOSSLClientHandler on an Apple platform.

```swift
let tlsConfiguration = TLSConfiguration.forClient()
let sslContext = try! NIOSSLContext(configuration: tlsConfiguration)

let eventLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)

ClientBootstrap(group: eventLoopGroup)
    .channelInitializer { channel in
        let sslHandler = try! NIOSSLClientHandler(context: sslContext, serverHostname: nil, customVerificationCallback: {_, _ in
        })
        return channel.pipeline.addHandler(sslHandler)
    }.connect(host: "localhost", port: 443)
```

When initializing NIOSSLClientHandler, `SSLConnection.customVerificationManager` is set twice which triggers the assertion.

First time:
https://github.com/apple/swift-nio-ssl/blob/e14f8ebd6a919c5cf9bbbacaf5245e38ecdb8352/Sources/NIOSSL/SSLContext.swift#L252-L260

Second time:
https://github.com/apple/swift-nio-ssl/blob/e14f8ebd6a919c5cf9bbbacaf5245e38ecdb8352/Sources/NIOSSL/NIOSSLClientHandler.swift#L71-L73

**Comment by Lukasa** [comment]
Yeah, I think that assertion is overly fussy. I will double-check this, but I’m pretty sure the code behaves entirely reasonably in the face of setting this callback twice.
