### ISSUE TITLE
throwing/not throwing overloads confusing the compiler sometimes?

### ISSUE THREAD

**Issue by ktoso** [apple/swift-nio-ssl#236]
We got some reports that the commit https://github.com/apple/swift-nio-ssl/commit/5a6ad123afa70242b69ffaac482b84dfef5907bd#diff-db823eaf0b560c341937445201794f0d which added 

```
 public convenience init(context: NIOSSLContext) {
public convenience init(context: NIOSSLContext, customVerificationCallback: @escaping NIOSSLCustomVerificationCallback) {
```

but kept

```
@available(*, deprecated, renamed: "init(context:serverHostname:customVerificationCallback:)")
public init(context: NIOSSLContext, verificationCallback: NIOSSLVerificationCallback? = nil) throws {
```
(notice the throws on the old function, and lack thereof in the new).

is causing 

```
 note: did you mean to handle error as optional value?
                                 let sslHandler = NIOSSLServerHandler(context: sslContext)
                                                  ^
                                                  try? 
```

in projects... I'm building with warnings as errors, so I can't just add the try there anyway, since that'd break compilation because it'd be a try in position where no throwing function exists.

Should the overloads have kept the same throwing behavior as the old init they deprecate?

**Comment by Lukasa** [comment]
Building with warnings as errors does not make this a Semver issue, sadly. The API continues to function, it merely warns. You can solve this by raising the minimum NIO version you support.

**Comment by ktoso** [comment]
Overall I agree and let’s close this one.
