### ISSUE TITLE
Don't report uncleanShutdown when we get EOF during a handshake

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-ssl#253]
If we're in the middle of a TLS handshake, and we get channelInactive, we currently report this as `uncleanShutdown`. That's not really a good error here: we need to say something more authoritative, like handshake failed.

**Comment by agnosticdev** [comment]
Should we close this?

**Comment by Lukasa** [comment]
Yup!

**Comment by weissi** [comment]
Just as an FYI to others: as of yesterday, this is also released
