### ISSUE TITLE
Compilation fails for Swift version 5.3-dev (LLVM 69d8678431d3eee, Swift e1aef96b7fea59b)

### ISSUE THREAD

**Issue by SercanKaraoglu** [apple/swift-nio-ssl#254]
I am using Tensorflow for Swift toolchain for my project. After upgrading to release V12 from https://github.com/tensorflow/swift/blob/master/Installation.md I started getting following error

```
139:7: error: missing '#include <stdlib.h>'; 'abort' must be declared before it is used
      abort();
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/stdlib.h:131:7: note: declaration here is not visible
void     abort(void) __cold __dead2;
```

This can be solved by including stdlib.h to CNIOBoringSSL_span.h

**Comment by Lukasa** [comment]
Thanks for filing this! However, this is a clang bug. Two lines above the include you added is an include of <cstdlib>. This is the exact same header, and should appropriately supply abort. It’s clang’s mistake to think it doesn’t. Please file this bug upstream with Tensorflow.
