### ISSUE TITLE
Updating from 1.1.0 to 1.2.0 broke my Xcode project.

### ISSUE THREAD

**Issue by guidomb** [apple/swift-nio-ssl#26]
Updating my project's dependencies by running `swift package update && swift package generate-xcodeproj` results in this package being update from 1.1.0 to 1.2.0 which broke my Xcode build (running swift build works fine).

It seems that the package cannot link against an OpenSSL-compatible library. I updated libressl and nothing changed. I also reverted to this package's version 1.1.0 and the Xcode project remains broken.

<img width="371" alt="screen shot 2018-07-29 at 12 59 59 pm" src="https://user-images.githubusercontent.com/390645/43368244-b0e49fa4-9330-11e8-9e17-945d1d68b2ca.png">

Based on [this](https://stackoverflow.com/questions/47096503/cleanly-handling-usr-local-with-swift-package-manager-and-libevent?noredirect=1&lq=1) StackOverflow answer and after adding the following snippet to my `Package.swift`:

```swift
    providers: [
      .brew([
        "libressl"
      ])
    ],
```

and getting the following error when running `swift package generate-xcodeproj`:

```
'BotEngine' /Users/guidomb/Documents/projects/wolox/BotEngine: error: configuration of package 'BotEngine' is invalid; the 'providers' property can only be used with a System Module Package
```

I wonder if the `libressl` provider should be added in this project's `Package.swift` file.

## Environment

 * Xcode version 9.4.1 (9F2000)
 * macOS version 10.13.6 (17G65)
 * Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
 * libressl: stable 2.7.4 (bottled), HEAD [keg-only] (installed with homebrew)

**Comment by guidomb** [comment]
I created a new project to see if I can reproduce the issue in my machine with a green field project and everything works fine. Here is the example `Package.swift`

```swift
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SSLTest",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
	.package(url: "https://github.com/apple/swift-nio-ssl", from: "1.2.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "SSLTest",
            dependencies: ["NIOOpenSSL"]),
    ]
)
```

**Comment by guidomb** [comment]
For some reason after updating my dependencies my Xcode project broke but only for that project. I've tried deleting the DerivedData folder, command + option + shift + K to delete all caches, re-generate the project using SPM and nothing worked. Any ideas on how to start with clean slate Xcode project?

**Comment by Lukasa** [comment]
`swift-nio-ssl-support` provides the link directive. Did you try deleting your XCode DerivedData as well as deleting your `.build` directory before reopening everything?

**Comment by Lukasa** [comment]
To start with a truly clean slate, close XCode, delete DerivedData, delete `.build` and then try again.

**Comment by guidomb** [comment]
OK doing all that worked. I think what actually helped was that I uninstalled libressl and install it again and then did what you told me. Maybe I would be helpful to add that to the README.md. Something like

> If you have any issue when linking your project with libressl try the following steps:
>  1. brew uninstall --force libressl
>  2. brew install libressl
>  3. rm -frd .build
>  4. rm -frd rm -frd ~/Library/Developer/Xcode/DerivedData/*
>  5. swift build && swift package generate-xcodeproj
>  6. Build Xcode project
