### ISSUE TITLE
Private key's file extension does not determine its type

### ISSUE THREAD

**Issue by aiden-leong** [apple/swift-nio-ssl#263]
```Bash
file /etc/letsencrypt/www.example.com/www.example.com.key 
/etc/letsencrypt/www.example.com/www.example.com.key: PEM RSA private key
```

https://github.com/apple/swift-nio-ssl/blob/cc0e80dbccf8c89c1f49c3a11c5929575035076c/Sources/NIOSSL/SSLContext.swift#L339-L360

`[ codes.vapor.application ] [ ERROR ] Could not configure TLS: failedToLoadPrivateKey (Vapor/HTTP/Server/HTTPServer.swift:333)`

**Comment by Lukasa** [comment]
You can load a private key directly from a file [and specify the serialization format directly](https://github.com/apple/swift-nio-ssl/blob/62bf5083df970e67c886210fa5b857eacf044b7c/Sources/NIOSSL/SSLPrivateKey.swift#L203.

**Comment by aiden-leong** [comment]
> You can load a private key directly from a file [and specify the serialization format directly](
> 
> https://github.com/apple/swift-nio-ssl/blob/62bf5083df970e67c886210fa5b857eacf044b7c/Sources/NIOSSL/SSLPrivateKey.swift#L203
> 
> .

```
// Enable TLS.
try app.http.server.configuration.tlsConfiguration = .forServer(
    certificateChain: [
        .certificate(.init(
            file: "/path/to/cert.pem",
            format: .pem
        ))
    ],
    privateKey: .file("/path/to/key.pem")
)
```
https://github.com/apple/swift-nio-ssl/blob/62bf5083df970e67c886210fa5b857eacf044b7c/Sources/NIOSSL/TLSConfiguration.swift#L39
https://github.com/apple/swift-nio-ssl/blob/cc0e80dbccf8c89c1f49c3a11c5929575035076c/Sources/NIOSSL/SSLContext.swift#L216-L223

* `case file(String, String)` might be better, otherwise, I will need to import this library directly to access `NIOSSLPrivateKey`.
* or remove `.file`. That will make `Vapor` provide a wrapper of `NIOSSLSerializationFormats`, and we will be happy too.

**Comment by Lukasa** [comment]
> - `case file(String, String)` might be better, otherwise, I will need to import this library directly to access `NIOSSLPrivateKey`

Sadly we cannot change the enumeration without breaking the API. This would require a deprecate-and-replace of the API, which doesn’t immediately solve your issue as it requires a Vapor code change to move to the new API.

> or remove `.file`. That will make `Vapor` provide a wrapper of `NIOSSLSerializationFormats`, and we will be happy too.

We can’t make breaking API changes at this time, as noted above. Even if we could, it’s not the best strategy. Vapor is an open source project run by helpful volunteers: if we need them to add an API, we can simply ask them to add it! @0xTim @gwynne are you happy to add an API that will accept a `NIOSSLPrivateKey` and `[NIOSSLCertificate]` for configuring TLS?

**Comment by aiden-leong** [comment]
@Lukasa Thanks.

If we stick to the current API, how about the `file` command?

**Comment by Lukasa** [comment]
I’m not sure I understand the question.

**Comment by 0xTim** [comment]
This looks like a Vapor issue - Vapor should provide the API to hook into https://github.com/apple/swift-nio-ssl/blob/62bf5083df970e67c886210fa5b857eacf044b7c/Sources/NIOSSL/SSLPrivateKey.swift#L203

**Comment by Lukasa** [comment]
Shiny, do we have an issue for this on Vapor we can link this to?

**Comment by aiden-leong** [comment]
@Lukasa We may judge its type by its content just like Linux `file` command does. In that way, Vapor won't need to change anything.

**Comment by Lukasa** [comment]
We are reluctant to do that because it is possible that the construction of this type is being done on an event loop thread. This file I/O will block the event loop, which we would like to avoid.

The preferred construction is to pre-load the certificates and keys using the alternative API.

**Comment by aiden-leong** [comment]
@Lukasa That sounds reasonable. Thanks!

**Comment by 0xTim** [comment]
> Shiny, do we have an issue for this on Vapor we can link this to?

There is not, @aiden-leong feel free to create an issue on vapor/vapor for this!

**Comment by aiden-leong** [comment]
@0xTim Sure!

**Comment by Lukasa** [comment]
Closing in favour of vapor/vapor#2550
