### ISSUE TITLE
Consider renaming this project to NIOSSL

### ISSUE THREAD

**Issue by gmosx** [apple/swift-nio-ssl#29]
There is no reason to use the 'Open' part in the name.
Also consider using the 'TLS' postfix for the whole project, e.g.:

```swift
swift-nio-tls
NIOTLS
```

The fact that you use OpenSSL and friends is an implementation detail, it shouldn't be reflected in the name of the package.

**Comment by Lukasa** [comment]
I don’t think the use of OpenSSL is an implementation detail: it’s a hard linkage requirement, our data types are strongly influenced by OpenSSL’s, and we have no plan to support non-OpenSSL backends in this API. As the README notes, this repo supports only OpenSSL and compatible libraries. So I think it’s fine.
