### ISSUE TITLE
support for OpenSSL 1.1 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-ssl#30]
As soon as we have CI for 18.04 (cf. https://github.com/apple/swift-nio/pull/604) we should get #20 merged which gives us support for OpenSSL 1.0 & 1.1. #20 has bit-rotted a little but shouldn't be too bad.

**Comment by tomerd** [comment]
+1 requires https://github.com/apple/swift-nio-ssl/pull/33

**Comment by Lukasa** [comment]
Ok #33 is landed, you should be able to move forward @tomerd.

**Comment by Lukasa** [comment]
Done, shipped in 1.3.0. Landed in #20.
