### ISSUE TITLE
Certificate configuration for client with makeClientConfiguration

### ISSUE THREAD

**Issue by jc4432** [apple/swift-nio-ssl#304]
On version 2.13.1 I used something similar to

`tlsConfiguration: .forClient(
            certificateChain: try NIOSSLCertificate.fromPEMFile("cert.pem").map { .certificate($0) },
                privateKey: .file("key.pem"))`

looks like version 2.14 has us using `makeClientConfiguration` and I can't figure out how to configure certificates for the client. I thought it would be something like the server configuration:

`tlsConfiguration: .makeClientConfiguration(
            certificateChain: try NIOSSLCertificate.fromPEMFile("cert.pem").map { .certificate($0) },
                privateKey: .file("key.pem"))`

but there doesn't seem to be any available parameters for makeClientConfiguration. On the front page it says 

> For clients, it is a bit simpler as there is no need to have a certificate chain or private key (though clients may have these things)

so it should at least be supported, what am I doing wrong?

**Comment by jc4432** [comment]
well... turns out I just need to create the configuration and set the properties then...

`var clientConfig = TLSConfiguration.makeClientConfiguration()
clientConfig.certificateChain: try NIOSSLCertificate.fromPEMFile("cert.pem").map { .certificate($0) }
clientConfig.privateKey: .file("key.pem")`

tlsConfiguration: clientConfig`

I see the idea behind it is we only have parameters for required fields in the server configuration and client configuration its optional...

**Comment by Lukasa** [comment]
Yes, this is correct. Specifically this reduces the churn of deprecations: each time we added a field to the TLSConfiguration struct we had to add two new initializers and deprecate two existing ones, which rapidly became a problem. We will not have to do this in future.
