### ISSUE TITLE
Make CI jobs for Swift 4.2 & Ubuntu 18.04

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-ssl#31]
Similar to https://github.com/apple/swift-nio/issues/606 we need CI jobs for 18.04 here. But before doing this, we need to fix #30.

In total I think we need the following new CI jobs (ordered by how important @weissi thinks they are):

- [x] Swift 4.2 on Ubuntu 18.04
- [ ] Swift 4.2 on Ubuntu 16.04
- [ ] Swift 4.2 on Ubuntu 14.04

note: there are no Swift 4.0 or 4.1 binaries available for Ubuntu 18.04, hence we won't have Swift 4.0 or 4.1 on Ubuntu 18.04

**Comment by weissi** [comment]
@tomerd / @Lukasa I think we can close this as we don't really need 4.2 on 14/16.04 or does anybody think we do?

**Comment by Lukasa** [comment]
I'm fine without I think.
