### ISSUE TITLE
How I can user secure enclave SecKey with nio-ssl?

### ISSUE THREAD

**Issue by aniljha24** [apple/swift-nio-ssl#314]
To make a secure grpc connection I need to provide private key.. but In my project private key is in secure enclave.. Is there any workaround to user secure enclave SecKey with NIO SSL ..

**Comment by Lukasa** [comment]
At this time this is not practical. However, there's scope for us to add support for custom callback-based private keys in the future using the `SSL_PRIVATE_KEY_METHOD` support in BoringSSL, which would enable this use-case.

**Comment by Lukasa** [comment]
See #322.
