### ISSUE TITLE
Swift REPL Support

### ISSUE THREAD

**Issue by jaderfeijo** [apple/swift-nio-ssl#343]
SwiftNIO commit hash: `21b7349c957546219a509c110859b08fb2bbf262 `

### Context:

While trying to use the `NIOSSL` library (or a library that depends on it) with the Swift REPL via `swift run --repl`, the following error occurs:

```
<module-includes>:1:9: note: in file included from <module-includes>:1:<module-includes>:1:
#import "/Users/jaderfeijo/Developer/swift-nio-ssl/Sources/CNIOBoringSSLShims/include/CNIOBoringSSLShims.h"
        ^

error: /Users/jaderfeijo/Developer/swift-nio-ssl/Sources/CNIOBoringSSLShims/include/CNIOBoringSSLShims.h:22:10: error: 'CNIOBoringSSL.h' file not found
#include "CNIOBoringSSL.h"
         ^
```

Steps to reproduce:
1. Checkout the commit in question
2. `cd` into the root directory of the project
3. Run `swift run --repl`
4. In the REPL, type in `import NIOSSL`

The error above will occur.

$ swift --version
> swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
> Target: arm64-apple-macosx12.0

Operating system: macOS Monterey 12.2

> Observation: This also has been observed on Ubuntu running Swift 5.5, both when running in `x86_64` and `arm64` architectures.

$ uname -a
> Darwin `<redacted>` 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

My system has IPv6 enabled.

**Comment by Lukasa** [comment]
Hmm, I don't think this project is responsible for this issue: do you mind filing a bug report on bugs.swift.org?

Cory

**Comment by jaderfeijo** [comment]
@Lukasa yes, I was wondering the same tbh. It might very well be an issue with how the swift REPL is loading the library.

I will do that 👍🏼

Shall I close this issue?

**Comment by jaderfeijo** [comment]
Issue created here: https://bugs.swift.org/browse/SR-15814

**Comment by Lukasa** [comment]
Thanks for filing that!
