### ISSUE TITLE
SSLCertificateTest.testNotValidAfter fails on Android armv7 and likely other 32-bit platforms

### ISSUE THREAD

**Issue by finagolfin** [apple/swift-nio-ssl#344]
Somebody recently reported problems using this package on Android armv7, termux/termux-packages#8569, so I had him run the tests for this package on there and he reported this test failing. I reproduced and looked into it today: the issue is an overflow when [trying to put too large a UNIX epoch time in seconds into `time_t`](https://github.com/apple/swift-nio-ssl/commit/58b355e5dc68a05c0c69ec14a1f44bdb94791e7c#diff-a9515aaeded6b0c424bee2094c34bca1ed80807fbb9c13264513d51ff4c7850aR540), which is a 32-bit signed integer on Android armv7.

That test has a certificate valid till 2047, which is too long so it fails; you should be able to reproduce on any other 32-bit platform with a similar `time_t`.

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by Lukasa** [comment]
Sure, feel free.
