### ISSUE TITLE
Specify TLS Provider for Swift gRPC Client Connection

### ISSUE THREAD

**Issue by WiseNN** [apple/swift-nio-ssl#419]
### What are you trying to achieve?

Is it possible to use Swift gRPC with a custom TLS provider? (like openSSL v3?). The objective is to use a custom TLS provider that will work with the Swift gRPC framework. Has anyone done this before.

### What have you tried so far?

I found a SO post that looks like someone may have been able to do this in [C++](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html). 

I am looking to see if something similar is offered in this framework.

**Comment by Lukasa** [comment]
swift-nio-ssl does not support pluggable TLS backends.

**Comment by WiseNN** [comment]
@Lukasa  Got it, thanks. We are looking to be fips compliant. Currently not sure if Apple's Network framework is fips compliant (latest version). 

If it is compliant, is there is a chance that SWIFTNIO-SSL is still using Native iOS for the SSL connection so that its actually doing SWIFTNIO-SSL -> Apple SSL -> Boring SSL. Can you confirm this? I am aware that we can use a client configuration backed by the network framework.

**Comment by Lukasa** [comment]
Network.framework is the way you use native iOS TLS.
