### ISSUE TITLE
Does swift-nio-ssl support windows 11 ?

### ISSUE THREAD

**Issue by reddream** [apple/swift-nio-ssl#432]
I am adding some ciphers into swift-nio-ssl to support mac/ios, but I am working on windows 11 and use swfit for windows to build it (I do not have mac env). 
There are some errors during compiling , and I see the macro below in SSLContext.swift 

#if os(macOS) || os(iOS) || os(watchOS) || os(tvOS)
import Darwin.C
#elseif os(Linux) || os(FreeBSD) || os(Android)
import Glibc
#else
#error("unsupported os")
#endif

It seems that this prj does not support windows , right ?

**Comment by Lukasa** [comment]
swift-nio (our critical dependency) does not support Windows, and until it does this project cannot support it either.

**Comment by reddream** [comment]
Got it. 
I plan to add ciphers using boringssl with commit abfd5ebc87ddca0fab9fca067c9d7edbc355eae8 in windows. then migrate the code of ciphters into swift-nio-ssl/Sources/CNIOBoringSSL, changing struct NIOTLSCipher in TLSConfiguration.swift. 
In your opion , is there any issues in adding self-defined ciphers?

**Comment by Lukasa** [comment]
We do not carry patches to BoringSSL in this codebase, so if you need to add things to CNIOBoringSSL you'll need to get them added upstream in BoringSSL.
