### ISSUE TITLE
Certificate tests started failing today

### ISSUE THREAD

**Issue by finagolfin** [apple/swift-nio-ssl#440]
I haven't bothered dumping them to check the dates, but the exact same `TLSConfigurationTest.testFullVerificationWithCANamesFrom{Certificate,File}` tests that passed yesterday [started failing on my daily Android CI today](https://github.com/finagolfin/swift-android-sdk/actions/runs/5830798355/job/15815405738#step:3:9344). I'm guessing the certs added for these tests in #307 expired today.

**Comment by Lukasa** [comment]
Given when that PR was added, sure seems likely!

**Comment by Lukasa** [comment]
For now I recommend disabling those tests locally, we'll probably only get to this on Monday.
