### ISSUE TITLE
customVerificationCallback not fired.

### ISSUE THREAD

**Issue by Therealnaxos** [apple/swift-nio-ssl#461]
It seems like the `customVerificationCallback` does not fire what so ever in the constructor: `NIOSSLServerHandler(context: , customVerificationCallback: )`.

I have tried setting the `TLSConfiguration` to a bunch of different states/configs. But no combination seem to trigger the custom verification callback.

Is this a bug, or a misconfiguration on my part?

Best regards.

_Sample code:_
```swift

      func customVerf(certs: [NIOSSLCertificate], result: EventLoopPromise<NIOSSLVerificationResult>) {
        print("Hello from customVerf!") // this should be printed but it does not for some reason...
        return result.succeed(.certificateVerified)
      }


       ......


      let (cert, key) = try generateSelfSignedTLSIdentity()
      var tlsConf = TLSConfiguration.makeServerConfiguration(certificateChain: [.certificate(cert)], privateKey: .privateKey(key))
      tlsConf.trustRoots = NIOSSLTrustRoots.certificates([cert])
      tlsConf.certificateVerification = .fullVerification
      let sslContext = try NIOSSLContext(configuration: tlsConf)

      let bootstrap = NIOTSListenerBootstrap(group: group)
        .serverChannelOption(ChannelOptions.socketOption(.so_reuseaddr), value: 1)
        .childChannelInitializer { channel in
          channel.pipeline.addHandler(NIOSSLServerHandler(context: sslContext, customVerificationCallback: self.customVerf), position: .first)
            .flatMap {
              channel.pipeline.addHandler(MyCustomHandler())
            }
        }
      let channel = try bootstrap
        .bind(host: host, port: port)
        .wait()

      try channel.closeFuture.wait()
```

**Comment by Lukasa** [comment]
Thanks for filing this! Is the client sending certs? If the client sends no certificates at all, the server will reject the handshake entirely and never get to the custom verification callback.

**Comment by Lukasa** [comment]
For me locally, if I use `openssl s_client` to connect _without_ passing `-cert` and `-key`, I see an error and the callback isn't called. If I do pass those two arguments, I see the callback invoked appropriately.
