### ISSUE TITLE
How to be notified when SSL/TLS handshake is done

### ISSUE THREAD

**Issue by xVanTuring** [apple/swift-nio-ssl#465]
I'm currently try to add NIOSSL(Client/Server)Handler dynamically, after received first custom identity data. I was able to use `channel.pipeline.addHandler` to do that, but I could find a way to get notified when the handshake is completed.

I noticed that in `NIOHTTP1`, we have a `configureUpgradableHTTPClientPipeline` extension function which will return a upgrade result. Can we provide something like that?

**Comment by Lukasa** [comment]
The `NIOSSLHandler` fires a user event down the channel pipeline when it completes the handshake: specifically, it fires [one of these two](https://github.com/apple/swift-nio/blob/9428f62793696d9a0cc1f26a63f63bb31da0516d/Sources/NIOTLS/TLSEvents.swift#L18-L26) depending on the outcome. You can see an example of how it is used in [grpc-swift](https://github.com/grpc/grpc-swift/blob/3c66c5f29a88d6ef1d60ec6242121e8ed58350cd/Sources/GRPC/GRPCServerPipelineConfigurator.swift#L301-L315).
