### ISSUE TITLE
Feature Request: Key type detection and (optional?) validation

### ISSUE THREAD

**Issue by mura-admin** [apple/swift-nio-ssl#47]
Currently the logic uses a best guess mechanism based on the extension. I noticed that this can fail for a .key extension with PEM formatting and the key type has to be explicitly passed in. Would be an improvement if for ambiguous extensions like .key that the format is automatically determined. Presumably OpenSSL doesn't have detect keytype api call already or it would have been used?

**Comment by mura-admin** [comment]
Specifically this line here that caused my issue with incorrect key type from file: https://github.com/apple/swift-nio-ssl/blob/master/Sources/NIOOpenSSL/SSLContext.swift#L340

**Comment by Lukasa** [comment]
We can definitely add code to perform a heuristic to detect key types. It will require us to handle the file I/O ourselves, but that's not the end of the world at all.

**Comment by Lukasa** [comment]
This is no longer relevant with the current codebase.
