### ISSUE TITLE
Is  SwiftNIO SSL supporting openssl 3.0  ?

### ISSUE THREAD

**Issue by kanjsahu** [apple/swift-nio-ssl#477]
Hi Team , 

As we know boringssl is fork of openssl , and openssl latest version is 3.0.
So our SwiftNIO SSL lib which is using boringssl is also supporting openssl's 3.0 features or not?

**Comment by Lukasa** [comment]
This is fundamentally not a question for Swift NIO SSL. We support exactly the features that BoringSSL supports. It has diverged _significantly_ from OpenSSL after its fork, and does not look like OpenSSL 3.
