### ISSUE TITLE
Update CI for Swift 5 support

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-ssl#62]
I have just cut a new release for the 1.X series (1.4) and pushed a maintenance branch for that release. We should now cut this repo over for the `master` branch to track development towards SwiftNIO 2 and SwiftNIO SSL 2.

@tomerd, can you change the CI on the `master` branch for this repository to build only against Swift 5 please, as we've done elsewhere? Can you then keep the current CI pointing at the branch called `nio-ssl-1.4`? Thanks a bunch.

**Comment by tomerd** [comment]
@Lukasa plz merge https://github.com/apple/swift-nio-ssl/pull/63 and i will finish up the CI side

**Comment by tomerd** [comment]
@Lukasa should be all god, give it a spin

**Comment by weissi** [comment]
done
