### ISSUE TITLE
How to generate private key using NIOOpenSSL or CNIOOpenSSL?

### ISSUE THREAD

**Issue by v57** [apple/swift-nio-ssl#78]
I need to generate rsa private key on my server for my api

**Comment by Lukasa** [comment]
I’m afraid that NIOOpenSSL is not intended as a general purpose cryptography library, and does not provide tools for generating private keys. While it is possible to use CNIOOpenSSL to do it I *strongly* advise against it, as that interface is not stable and may break without warning. 

In this case I recommend using a general purpose cryptography library to do this: something like BlueCryptor or Vapor/crypto would do the trick.
