### ISSUE TITLE
NIOSSLClientHandler should not have a default have for serverHostname

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-ssl#80]
It's too easy to forget to pass `serverHostname` so we shouldn't make it have a default value. Users can still pass `nil` in there but they should be required to pass something

https://github.com/apple/swift-nio-ssl/blob/45fa2eb1afc325ceaf9e2ea077bddce25b11271a/Sources/NIOSSL/NIOSSLClientHandler.swift#L34

**Comment by weissi** [comment]
@ktoso this could maybe be your prob?

**Comment by ktoso** [comment]
I'll check :)
