### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Lojii** [apple/swift-nio-ssl#93]
How to support iOS ？

**Comment by Lukasa** [comment]
iOS should work fine. Can you please provide information about what version you’re building and what errors you are seeing?

**Comment by Lojii** [comment]
Just arm64, There is no such problem in the simulator.
<img width="619" alt="Snipaste_2019-03-28_19-45-05" src="https://user-images.githubusercontent.com/11417737/55155357-1c193580-5192-11e9-9d58-6a7fd28a4600.png">

**Comment by Lukasa** [comment]
Which version of swift-nio-ssl? What are your build settings (including target OS?£

**Comment by Lojii** [comment]
swift-nio-ssl 2.0.0, The previous version did not have this problem .
<img width="446" alt="Snipaste_2019-03-28_20-26-17" src="https://user-images.githubusercontent.com/11417737/55157625-d9f2f280-5197-11e9-9d4c-70e5fd76fd7c.png">

**Comment by Lukasa** [comment]
What iOS version are you targeting?

**Comment by Lojii** [comment]
12.0

**Comment by Lukasa** [comment]
And what Xcode version?

**Comment by Lojii** [comment]
10.2 , swift 5.0

**Comment by Lukasa** [comment]
I have not been able to reproduce this so far. Have you tried removing the `.build` directory and your Xcode derived data, as well as the xcodeproj file, and regenerating?

**Comment by Lojii** [comment]
When I try to compile CNIOBoringSSL, I get an error, but this error only occur in the arm64 architecture, not in the x86_64 architecture. I'll try something else. Thanks

**Comment by weissi** [comment]
@Lojii any updates here?

**Comment by weissi** [comment]
@Lojii friendly ping, can we close this?

**Comment by weissi** [comment]
closing this issue because it has gone stale.
