### ISSUE TITLE
Channel close does not timeout

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-nio-ssl#96]
The `SSLHandler` performing TLS shutdown doesn't timeout after sending close notify (e.g. in cases where the remote peer does not send a close notify in response). 

One result of this is the close promise never being fulfilled, which is particularly bad if users are `wait()`-ing on it.

**Comment by Lukasa** [comment]
Yup, this has been a feature we've been missing for quite a while: we should really add it.

**Comment by glbrntt** [comment]
Fixed by #100
